### ISSUE TITLE
Does not work with urllib3 >= 2.0.0

### ISSUE THREAD

**Issue by oschwald** [mindflayer/python-mocket#199]
As of `urlib3` 2.0.0, we are seeing failures such as the following:

```
======================================================================
ERROR: webservice_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: webservice_test
Traceback (most recent call last):
  File "/home/greg/.pyenv/versions/3.10.0/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/greg/MaxMind/GeoIP2-python/tests/webservice_test.py", line 16, in <module>
    from mocket import Mocket  # type: ignore
  File "/home/greg/MaxMind/GeoIP2-python/.eggs/mocket-3.11.0-py3.10.egg/mocket/__init__.py", line 1, in <module>
    from .async_mocket import async_mocketize
  File "/home/greg/MaxMind/GeoIP2-python/.eggs/mocket-3.11.0-py3.10.egg/mocket/async_mocket.py", line 1, in <module>
    from .mocket import Mocketizer
  File "/home/greg/MaxMind/GeoIP2-python/.eggs/mocket-3.11.0-py3.10.egg/mocket/mocket.py", line 18, in <module>
    from urllib3.util.ssl_ import wrap_socket as urllib3_wrap_socket
ImportError: cannot import name 'wrap_socket' from 'urllib3.util.ssl_' (/home/greg/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/util/ssl_.py)
```

This is for the tests in the [`geoip2` package](https://github.com/maxmind/GeoIP2-python), but I don't know that the failure is particular to anything we are doing.

**Comment by mindflayer** [comment]
I'll have a look at it. Thanks for reporting the issue.

**Comment by mindflayer** [comment]
@oschwald could you please test out my changes? I guess it should be enough to make it work.

**Comment by mindflayer** [comment]
@oschwald could you please test out the code from the above PR? Tests are failing because they rely A LOT on httpbin.org and it's returning some BAD GATEWAY here and there. I have a plan to replace it with a Docker container, but it was not an easy change and I had no time to complete it.

**Comment by mindflayer** [comment]
Enjoy the new version of Mocket: https://pypi.org/project/mocket/3.11.1/

**Comment by oschwald** [comment]
Thanks! The new version seems to work well.
